server:
  port: 8083

spring:
  application:
    name: ratingService
  datasource:
    url: jdbc:h2:mem:ratingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
